/*
 总结：
 通过对这个App的开发，了解了
 1、UIKit基本控件的用法
 2、有关App布局的基本操作方法
 3、有关应用实现逻辑的初步理解
 在这个App中，还有些不足需要补充
 1、对Date，NSDate，Calender，NSCalender知识点的补充
 2、梳理一个App的基本构架及基本逻辑
 3、对Storyboard进行更加美观的优化
 4、对UIButton里面的方法进行多次尝试
 */
